sudo: required


os:
  - linux

language: c
dist: xenial
services:
  - xvfb

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

addons:
  firefox: "60.0.1"

install:
  - export CHOOSENIM_CHOOSE_VERSION="#d2f7ecb80"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y

script:
  # set firefox as default browser. Otherwise google-chrome is picked for some
  # reason
  - export BROWSER=firefox
  - nimble install -y
  - nimble -y travisTest